/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as PoliciesRefundsRouteImport } from './routes/policies.refunds'
import { Route as PoliciesShippingRouteImport } from './routes/policies.shipping'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin.admin_.analytics'
import { Route as AdminAdminCouponsRouteImport } from './routes/_admin.admin_.coupons'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin.admin_.customers'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin.admin_.orders'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin.admin_.products'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin.admin_.reviews'
import { Route as AdminAdminOrdersIdRouteImport } from './routes/_admin.admin_.orders.$id'
import { Route as AdminAdminProductsIdRouteImport } from './routes/_admin.admin_.products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundsRoute = PoliciesRefundsRouteImport.update({
  id: '/policies/refunds',
  path: '/policies/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesShippingRoute = PoliciesShippingRouteImport.update({
  id: '/policies/shipping',
  path: '/policies/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin_/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCouponsRoute = AdminAdminCouponsRouteImport.update({
  id: '/admin_/coupons',
  path: '/admin/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/admin_/customers',
  path: '/admin/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin_/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin_/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/admin_/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersIdRoute = AdminAdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminOrdersRoute,
} as any)
const AdminAdminProductsIdRoute = AdminAdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/track': typeof TrackRoute
  '/admin': typeof AdminAdminRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/orders/$id': typeof AdminAdminOrdersIdRoute
  '/admin/products/$id': typeof AdminAdminProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/track': typeof TrackRoute
  '/admin': typeof AdminAdminRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/orders/$id': typeof AdminAdminOrdersIdRoute
  '/admin/products/$id': typeof AdminAdminProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/track': typeof TrackRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refunds': typeof PoliciesRefundsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_admin/admin_/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin_/coupons': typeof AdminAdminCouponsRoute
  '/_admin/admin_/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin_/orders': typeof AdminAdminOrdersRouteWithChildren
  '/_admin/admin_/products': typeof AdminAdminProductsRouteWithChildren
  '/_admin/admin_/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin_/orders/$id': typeof AdminAdminOrdersIdRoute
  '/_admin/admin_/products/$id': typeof AdminAdminProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/track'
    | '/admin'
    | '/api/assistant'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/shipping'
    | '/policies/terms'
    | '/product/$slug'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/orders/$id'
    | '/admin/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/track'
    | '/admin'
    | '/api/assistant'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/shipping'
    | '/policies/terms'
    | '/product/$slug'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/orders/$id'
    | '/admin/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/checkout'
    | '/track'
    | '/_admin/admin'
    | '/api/assistant'
    | '/policies/privacy'
    | '/policies/refunds'
    | '/policies/shipping'
    | '/policies/terms'
    | '/product/$slug'
    | '/_admin/admin_/analytics'
    | '/_admin/admin_/coupons'
    | '/_admin/admin_/customers'
    | '/_admin/admin_/orders'
    | '/_admin/admin_/products'
    | '/_admin/admin_/reviews'
    | '/_admin/admin_/orders/$id'
    | '/_admin/admin_/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  TrackRoute: typeof TrackRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesRefundsRoute: typeof PoliciesRefundsRoute
  PoliciesShippingRoute: typeof PoliciesShippingRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refunds': {
      id: '/policies/refunds'
      path: '/policies/refunds'
      fullPath: '/policies/refunds'
      preLoaderRoute: typeof PoliciesRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/shipping': {
      id: '/policies/shipping'
      path: '/policies/shipping'
      fullPath: '/policies/shipping'
      preLoaderRoute: typeof PoliciesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin_/analytics': {
      id: '/_admin/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin_/coupons': {
      id: '/_admin/admin_/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminAdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin_/customers': {
      id: '/_admin/admin_/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin_/orders': {
      id: '/_admin/admin_/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin_/products': {
      id: '/_admin/admin_/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin_/reviews': {
      id: '/_admin/admin_/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin_/orders/$id': {
      id: '/_admin/admin_/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminAdminOrdersIdRouteImport
      parentRoute: typeof AdminAdminOrdersRoute
    }
    '/_admin/admin_/products/$id': {
      id: '/_admin/admin_/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminAdminProductsIdRouteImport
      parentRoute: typeof AdminAdminProductsRoute
    }
  }
}

interface AdminAdminOrdersRouteChildren {
  AdminAdminOrdersIdRoute: typeof AdminAdminOrdersIdRoute
}

const AdminAdminOrdersRouteChildren: AdminAdminOrdersRouteChildren = {
  AdminAdminOrdersIdRoute: AdminAdminOrdersIdRoute,
}

const AdminAdminOrdersRouteWithChildren =
  AdminAdminOrdersRoute._addFileChildren(AdminAdminOrdersRouteChildren)

interface AdminAdminProductsRouteChildren {
  AdminAdminProductsIdRoute: typeof AdminAdminProductsIdRoute
}

const AdminAdminProductsRouteChildren: AdminAdminProductsRouteChildren = {
  AdminAdminProductsIdRoute: AdminAdminProductsIdRoute,
}

const AdminAdminProductsRouteWithChildren =
  AdminAdminProductsRoute._addFileChildren(AdminAdminProductsRouteChildren)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminCouponsRoute: typeof AdminAdminCouponsRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRouteWithChildren
  AdminAdminProductsRoute: typeof AdminAdminProductsRouteWithChildren
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminCouponsRoute: AdminAdminCouponsRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRouteWithChildren,
  AdminAdminProductsRoute: AdminAdminProductsRouteWithChildren,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  TrackRoute: TrackRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesRefundsRoute: PoliciesRefundsRoute,
  PoliciesShippingRoute: PoliciesShippingRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
